/*
 * This source file was generated by the Gradle 'init' task
 */
package de.bellian.hytale.test;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    
}
