/*
 * This source file was generated by the Gradle 'init' task
 */
package de.bellian.hytale.test;

import com.hypixel.hytale.component.ComponentRegistryProxy;
import com.hypixel.hytale.component.system.ISystem;
import com.hypixel.hytale.server.core.plugin.JavaPlugin;
import com.hypixel.hytale.server.core.plugin.JavaPluginInit;
import com.hypixel.hytale.server.core.universe.world.storage.EntityStore;

import de.bellian.hytale.test.commands.HelloCommand;
import de.bellian.hytale.test.commands.HelloWorldCommand;
import de.bellian.hytale.test.systems.FixGameTime;

import javax.annotation.Nonnull;

public class App extends JavaPlugin {
    public App(@Nonnull JavaPluginInit init) {
        super(init);
    }

    @Override
    protected void setup() {
        super.setup();

        ComponentRegistryProxy<EntityStore> entityStoreRegistry = getEntityStoreRegistry();
        entityStoreRegistry.registerSystem((ISystem<EntityStore>)new FixGameTime());

        this.getCommandRegistry().registerCommand( new HelloCommand("hello", "Shows a hello world title", false));
        getCommandRegistry().registerCommand(new HelloWorldCommand());
    }

    public static void main(String[] args) {
        System.out.println(new App(null));
    }
}
